services:
  db-service:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - /home/deployer/data/postgres:/var/lib/postgresql/data
    healthcheck:
      # CAMBIO: Leemos los secretos reales para que pg_isready no use el usuario 'postgres' por defecto
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/db_user) -d $$(cat /run/secrets/db_name)"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - back-network
    secrets:
      - db_name
      - db_user
      - db_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend-service:
    image: backend:latest
    container_name: backend
    restart: always
    build:
      context: ./backend-build
      dockerfile: Dockerfile
    environment:
      SPRING_CONFIG_IMPORT: "optional:file:/run/secrets/spring_secrets.properties"
      SPRING_PROFILES_ACTIVE: ${BACK_PROFILE}
    depends_on:
      db-service:
        condition: service_healthy
    healthcheck:
      # CAMBIO: Unificamos a -qO- para limpiar los logs del contenedor de Spring
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - back-network
      - front-network
    secrets:
      - spring_secrets
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  frontend-service:
    image: frontend:latest
    container_name: frontend
    restart: always
    build:
      context: ./frontend-build
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - front-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
  orchestrator-nginx-service:
    build: ./nginx
    container_name: orchestrator-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      frontend-service:
        condition: service_healthy
      backend-service:
        condition: service_healthy
    healthcheck:
      # CAMBIO: Cambiamos el truco de Bash por wget, asumiendo que este Nginx también corre sobre Alpine/Debian
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - front-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge