services:
  db-service:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - /home/deployer/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/db_user) -d $$(cat /run/secrets/db_name)"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - back-network
    secrets:
      - db_name
      - db_user
      - db_password
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  backend-service:
    image: backend:latest
    scale: 1
    restart: always
    build:
      context: ./backend-build
      dockerfile: Dockerfile
    environment:
      SPRING_CONFIG_IMPORT: "optional:file:/run/secrets/spring_secrets.properties"
      SPRING_PROFILES_ACTIVE: ${BACK_PROFILE}
    depends_on:
      db-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - back-network
      - front-network
    secrets:
      - spring_secrets
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  frontend-service:
    build:
      context: ./frontend-build
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend-service
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - front-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  spring_secrets:
    file: ./secrets/spring_secrets.properties

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge