# =====================================================================
# MONITOR STACK CONFIGURATION PROPERTIES
# =====================================================================

# Space-separated list of target notification emails
ALERT_MAILS_LIST="your-email@gmail.com backup-alerts@gmail.com"
