# ==========================================
# 1. COMMON CONFIGURATION (Applies to all profiles)
# ==========================================
spring:
  application:
    name: project-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    org.springframework: INFO

---
# ==========================================
# 2. DEVELOPMENT PROFILE
# ==========================================
spring:
  config:
    activate:
      on-profile: dev

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

---
# ==========================================
# 3. PRODUCTION PROFILE
# ==========================================
spring:
  config:
    activate:
      on-profile: prod

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.orm.jdbc.bind: ERROR